// <auto-generated />
using System;
using DataModel.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataModel.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200315155721_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataModel.Data.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bed27949-bd09-47ee-a698-ec0830224c40"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("13909a3a-8d00-48da-8653-fab12e287757"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e8b98949-a614-47b5-bfc0-d942ac07d47a"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("e32fdaeb-d5bc-4410-9b21-bb553e0e77d3"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1258601a-dd8f-4d79-855a-ec61c02924e5"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("e32fdaeb-d5bc-4410-9b21-bb553e0e77d3"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("DataModel.Data.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13909a3a-8d00-48da-8653-fab12e287757"),
                            Address = "John's address",
                            Name = "John "
                        },
                        new
                        {
                            Id = new Guid("e32fdaeb-d5bc-4410-9b21-bb553e0e77d3"),
                            Address = "Jane's address",
                            Name = "Jane "
                        });
                });

            modelBuilder.Entity("DataModel.Data.Account", b =>
                {
                    b.HasOne("DataModel.Data.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
